"""Документы, эмбеддинги, фильтры, рекомендации, outbox

Revision ID: 0002_platform
Revises: 0001_baseline
Create Date: 2026-08-07 16:12:11.310778
"""

from collections.abc import Sequence

# Автогенерация рендерит столбцы как `pgvector.sqlalchemy.vector.VECTOR(...)`,
# но импорт для них не добавляет — держим его в шаблоне.
import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002_platform'
down_revision: str | None = '0001_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_digests',
    sa.Column('digest_date', sa.Date(), nullable=False),
    sa.Column('summary_md', sa.Text(), nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tender_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('digest_date')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='queued', nullable=False),
    sa.Column('total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('processed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('routing_key', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_outbox_published_at'), 'outbox', ['published_at'], unique=False)
    op.create_index(op.f('ix_outbox_routing_key'), 'outbox', ['routing_key'], unique=False)
    op.create_table('processed_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('consumer', sa.String(length=128), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'consumer', name='uq_processed_message')
    )
    op.create_index(op.f('ix_processed_messages_message_id'), 'processed_messages', ['message_id'], unique=False)
    op.create_table('recommendation_profiles',
    sa.Column('id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('okpd2_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('customer_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signal_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_filters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('nl_query', sa.Text(), nullable=True),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_criteria', sa.Text(), nullable=True),
    sa.Column('semantic_query', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_filters_is_active'), 'saved_filters', ['is_active'], unique=False)
    op.create_table('llm_verdicts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tender_id', sa.BigInteger(), nullable=False),
    sa.Column('filter_id', sa.BigInteger(), nullable=False),
    sa.Column('match', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['saved_filters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id', 'filter_id', 'prompt_version', name='uq_llm_verdict')
    )
    op.create_index(op.f('ix_llm_verdicts_filter_id'), 'llm_verdicts', ['filter_id'], unique=False)
    op.create_index(op.f('ix_llm_verdicts_tender_id'), 'llm_verdicts', ['tender_id'], unique=False)
    op.create_index('llm_verdicts_filter_match_idx', 'llm_verdicts', ['filter_id', 'match'], unique=False)
    op.create_table('recommendation_impressions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tender_id', sa.BigInteger(), nullable=False),
    sa.Column('shown_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id', name='uq_recommendation_impression')
    )
    op.create_index(op.f('ix_recommendation_impressions_tender_id'), 'recommendation_impressions', ['tender_id'], unique=False)
    op.create_table('tender_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tender_id', sa.BigInteger(), nullable=False),
    sa.Column('attachment_id', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('doc_kind_code', sa.Text(), nullable=True),
    sa.Column('doc_kind_name', sa.Text(), nullable=True),
    sa.Column('doc_description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('minio_key', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('extraction_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('ocr_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('nesting_depth', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('parent_document_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_document_id'], ['tender_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id', 'attachment_id', name='uq_tender_attachment')
    )
    op.create_index(op.f('ix_tender_documents_sha256'), 'tender_documents', ['sha256'], unique=False)
    op.create_index(op.f('ix_tender_documents_tender_id'), 'tender_documents', ['tender_id'], unique=False)
    op.create_index('tender_documents_status_idx', 'tender_documents', ['extraction_status'], unique=False)
    op.create_table('tender_embeddings',
    sa.Column('tender_id', sa.BigInteger(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('source_text_hash', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tender_id')
    )
    op.create_index('tender_embeddings_embedding_idx', 'tender_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('tender_feedback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tender_id', sa.BigInteger(), nullable=False),
    sa.Column('signal', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id', name='uq_tender_feedback')
    )
    op.create_index(op.f('ix_tender_feedback_tender_id'), 'tender_feedback', ['tender_id'], unique=False)
    op.create_table('tender_views',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tender_id', sa.BigInteger(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dwell_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_views_tender_id'), 'tender_views', ['tender_id'], unique=False)
    op.create_index(op.f('ix_tender_views_viewed_at'), 'tender_views', ['viewed_at'], unique=False)
    op.create_table('won_tenders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tender_id', sa.BigInteger(), nullable=False),
    sa.Column('won_at', sa.Date(), nullable=True),
    sa.Column('contract_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id', name='uq_won_tender')
    )
    op.create_index(op.f('ix_won_tenders_tender_id'), 'won_tenders', ['tender_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('tender_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_from', sa.Integer(), nullable=True),
    sa.Column('page_to', sa.Integer(), nullable=True),
    sa.Column('token_estimate', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', text)", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['tender_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunk')
    )
    op.create_index('document_chunks_embedding_idx', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('document_chunks_tsv_idx', 'document_chunks', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_tender_id'), 'document_chunks', ['tender_id'], unique=False)
    op.create_table('document_texts',
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('tender_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('extractor', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['tender_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_document_texts_tender_id'), 'document_texts', ['tender_id'], unique=False)
    op.add_column('crawler_runs', sa.Column('region', sa.String(length=8), nullable=True))
    op.add_column('crawler_runs', sa.Column('document_type', sa.Text(), nullable=True))
    op.add_column('crawler_runs', sa.Column('target_date', sa.Date(), nullable=True))
    op.add_column('crawler_runs', sa.Column('saved', sa.Integer(), server_default='0', nullable=False))
    op.add_column('crawler_runs', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('crawler_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('crawler_runs', 'fetched',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('crawler_runs', 'errors',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('crawler_runs', 'status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'running'::text"))
    op.add_column('tenders', sa.Column('region_code', sa.String(length=8), nullable=True))
    op.add_column('tenders', sa.Column('okpd2_codes', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('tenders', sa.Column('documents_status', sa.String(length=16), server_default='pending', nullable=False))
    op.add_column('tenders', sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', coalesce(name, '') || ' ' || coalesce(description, ''))", persisted=True), nullable=True))
    op.alter_column('tenders', 'reg_num',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tenders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('tenders_embedding_idx'), table_name='tenders', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_tenders_documents_status'), 'tenders', ['documents_status'], unique=False)
    op.create_index('tenders_end_date_idx', 'tenders', ['end_date'], unique=False)
    op.create_index('tenders_okpd2_codes_idx', 'tenders', ['okpd2_codes'], unique=False, postgresql_using='gin')
    op.create_index('tenders_search_tsv_idx', 'tenders', ['search_tsv'], unique=False, postgresql_using='gin')
    op.drop_column('tenders', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenders', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True))
    op.drop_index('tenders_search_tsv_idx', table_name='tenders', postgresql_using='gin')
    op.drop_index('tenders_okpd2_codes_idx', table_name='tenders', postgresql_using='gin')
    op.drop_index('tenders_end_date_idx', table_name='tenders')
    op.drop_index(op.f('ix_tenders_documents_status'), table_name='tenders')
    op.create_index(op.f('tenders_embedding_idx'), 'tenders', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('tenders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenders', 'reg_num',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('tenders', 'search_tsv')
    op.drop_column('tenders', 'documents_status')
    op.drop_column('tenders', 'okpd2_codes')
    op.drop_column('tenders', 'region_code')
    op.alter_column('crawler_runs', 'status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'running'::text"))
    op.alter_column('crawler_runs', 'errors',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('crawler_runs', 'fetched',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('crawler_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('crawler_runs', 'error_message')
    op.drop_column('crawler_runs', 'saved')
    op.drop_column('crawler_runs', 'target_date')
    op.drop_column('crawler_runs', 'document_type')
    op.drop_column('crawler_runs', 'region')
    op.drop_index(op.f('ix_document_texts_tender_id'), table_name='document_texts')
    op.drop_table('document_texts')
    op.drop_index(op.f('ix_document_chunks_tender_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index('document_chunks_tsv_idx', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('document_chunks_embedding_idx', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_won_tenders_tender_id'), table_name='won_tenders')
    op.drop_table('won_tenders')
    op.drop_index(op.f('ix_tender_views_viewed_at'), table_name='tender_views')
    op.drop_index(op.f('ix_tender_views_tender_id'), table_name='tender_views')
    op.drop_table('tender_views')
    op.drop_index(op.f('ix_tender_feedback_tender_id'), table_name='tender_feedback')
    op.drop_table('tender_feedback')
    op.drop_index('tender_embeddings_embedding_idx', table_name='tender_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('tender_embeddings')
    op.drop_index('tender_documents_status_idx', table_name='tender_documents')
    op.drop_index(op.f('ix_tender_documents_tender_id'), table_name='tender_documents')
    op.drop_index(op.f('ix_tender_documents_sha256'), table_name='tender_documents')
    op.drop_table('tender_documents')
    op.drop_index(op.f('ix_recommendation_impressions_tender_id'), table_name='recommendation_impressions')
    op.drop_table('recommendation_impressions')
    op.drop_index('llm_verdicts_filter_match_idx', table_name='llm_verdicts')
    op.drop_index(op.f('ix_llm_verdicts_tender_id'), table_name='llm_verdicts')
    op.drop_index(op.f('ix_llm_verdicts_filter_id'), table_name='llm_verdicts')
    op.drop_table('llm_verdicts')
    op.drop_index(op.f('ix_saved_filters_is_active'), table_name='saved_filters')
    op.drop_table('saved_filters')
    op.drop_table('recommendation_profiles')
    op.drop_index(op.f('ix_processed_messages_message_id'), table_name='processed_messages')
    op.drop_table('processed_messages')
    op.drop_index(op.f('ix_outbox_routing_key'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_published_at'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('daily_digests')
    # ### end Alembic commands ###
