/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tenders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tenders */
        get: operations["list_tenders_tenders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Tenders
         * @description Гибридный поиск: находит и по точным словам, и по смыслу.
         *
         *     Ищет в том числе по тексту приложенной документации — часть требований
         *     звучит только в ТЗ.
         */
        get: operations["search_tenders_tenders_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tender Facets
         * @description Счётчики по всей выдаче запроса, а не по текущей странице.
         *
         *     Параметры те же, что у `/tenders`: фасеты обязаны описывать ровно ту
         *     выдачу, которую видит пользователь.
         *
         *     Фасета «способ определения поставщика» здесь нет: ЕИС не передаёт его в
         *     `epNotificationEF2020`, и в `tenders` такой колонки не существует.
         */
        get: operations["tender_facets_tenders_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tender Groups
         * @description Оглавление сгруппированного списка: счётчик и сумма НМЦК на группу.
         *
         *     Считается по всей выдаче теми же условиями, что и `/tenders` — иначе
         *     сумма в шапке группы разойдётся со строками под ней.
         *
         *     Порядок групп совпадает с порядком строк при `sort=<group>:asc,…`, так
         *     что клиенту достаточно вставлять шапку при смене ключа группы.
         */
        get: operations["tender_groups_tenders_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{reg_num}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tender */
        get: operations["get_tender_tenders__reg_num__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{reg_num}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Similar Tenders
         * @description Похожие закупки по «карточному» эмбеддингу.
         *
         *     Пустой список — законный ответ: у свежей закупки вектора ещё нет.
         */
        get: operations["similar_tenders_tenders__reg_num__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{reg_num}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tender Events
         * @description Событийный след закупки: что публиковалось, что дошло, что застряло.
         *
         *     Статус выводится из outbox и таблицы обработанных, отдельной колонки нет:
         *     заводить её ради экрана значило бы дублировать то, что уже следует из данных.
         */
        get: operations["tender_events_tenders__reg_num__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Document
         * @description Ссылка на скачивание. Файл идёт из MinIO напрямую, минуя шлюз.
         */
        get: operations["download_document_documents__document_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document Text */
        get: operations["document_text_documents__document_id__text_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Document Chunks
         * @description Границы фрагментов внутри текста документа.
         *
         *     По ним `[Показать источник]` в ИИ-вердикте попадает в конкретное место, а не
         *     просто открывает документ. У чанков, нарезанных до появления смещений,
         *     `char_start`/`char_end` равны null — подсвечивать там нечего.
         */
        get: operations["document_chunks_documents__document_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Filters */
        get: operations["list_filters_filters_get"];
        put?: never;
        /** Save Filter */
        post: operations["save_filter_filters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filters/{filter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Filter */
        get: operations["get_filter_filters__filter_id__get"];
        put?: never;
        post?: never;
        /** Delete Filter */
        delete: operations["delete_filter_filters__filter_id__delete"];
        options?: never;
        head?: never;
        /** Patch Filter */
        patch: operations["patch_filter_filters__filter_id__patch"];
        trace?: never;
    };
    "/filters/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compile Filter
         * @description Превью структурного фильтра из свободного текста, без сохранения.
         */
        post: operations["compile_filter_filters_compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filters/{filter_id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicate Filter */
        post: operations["duplicate_filter_filters__filter_id__duplicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filters/{filter_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Filter
         * @description Запуск LLM-фильтрации. Прогон занимает минуты — отвечаем job_id.
         */
        post: operations["run_filter_filters__filter_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filters/{filter_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Filter
         * @description Пробный прогон: та же фильтрация, но с разбивкой по этапам отбора.
         *
         *     Результат приходит в `GET /jobs/{job_id}.result.funnel`.
         */
        post: operations["test_filter_filters__filter_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Status */
        get: operations["job_status_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/fragments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Fragments
         * @description Единица выдачи — фрагмент, а не закупка.
         *
         *     Режимы находят разное: лексический берёт точные термины и артикулы,
         *     векторный — смысл без общих слов, `rrf` объединяет их по рангам. Разложение
         *     оценок в ответе показывает, какая часть поиска нашла фрагмент.
         */
        get: operations["search_fragments_search_fragments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Digest Dates
         * @description За какие дни сводка уже есть — точки в календаре.
         */
        get: operations["digest_dates_digest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digest/{digest_date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Digest */
        get: operations["digest_digest__digest_date__get"];
        put?: never;
        /** Request Digest */
        post: operations["request_digest_digest__digest_date__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommendations */
        get: operations["recommendations_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feedback */
        post: operations["feedback_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** View */
        post: operations["view_views_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Win */
        post: operations["win_wins_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/weights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile Weights */
        get: operations["profile_weights_profile_weights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Profile Weight
         * @description `weight: null` снимает ручную правку и возвращает вычисленное значение.
         */
        patch: operations["patch_profile_weight_profile_weights_patch"];
        trace?: never;
    };
    "/profile/ranker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profile Ranker
         * @description Сколько сигналов есть и сколько нужно — порог приходит с сервера.
         */
        get: operations["profile_ranker_profile_ranker_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile History */
        get: operations["profile_history_profile_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/wins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile Wins */
        get: operations["profile_wins_profile_wins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/history/{signal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Rating
         * @description «Отменить оценку». Запись принадлежит recsys — он же по ней учится.
         */
        delete: operations["delete_rating_profile_history__signal_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitoring/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Services Health
         * @description Состояние сервисов одним ответом.
         *
         *     Сервис, который не ответил, помечается `down` — это факт о нём, а не
         *     ошибка страницы: иначе упавший прятал бы состояние остальных именно тогда,
         *     когда на экран и смотрят.
         */
        get: operations["services_health_monitoring_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitoring/queues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Queues
         * @description Глубины очередей, лестница повторов и недоставленные сообщения.
         */
        get: operations["queues_monitoring_queues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitoring/queues/dead-letters/{message_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Dead Letter */
        post: operations["retry_dead_letter_monitoring_queues_dead_letters__message_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitoring/crawler/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Crawler Runs */
        get: operations["crawler_runs_monitoring_crawler_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitoring/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Document Pipeline
         * @description Воронка обработки документов и отказы по этапам.
         */
        get: operations["document_pipeline_monitoring_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Settings
         * @description То, с чем процесс работает прямо сейчас, а не содержимое `.env`.
         *
         *     Секреты маскированы. `restart_required_keys` перечисляет ключи, которые
         *     читаются только на старте: правка без перезапуска ничего не изменит.
         */
        get: operations["settings_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/eis-token/rotated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Token Rotation
         * @description Отметка «токен перевыпущен».
         *
         *     Сам токен приходит из окружения и шлюзу неподвластен — записывается только
         *     факт и время.
         */
        post: operations["confirm_token_rotation_settings_eis_token_rotated_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CertificateOut */
        CertificateOut: {
            /** Subject */
            subject: string;
            /** Fingerprint */
            fingerprint: string;
            /** Not After */
            not_after: string | null;
        };
        /** ChunkOutlineOut */
        ChunkOutlineOut: {
            /** Chunk Id */
            chunk_id: number;
            /** Ordinal */
            ordinal: number;
            /** Char Start */
            char_start: number | null;
            /** Char End */
            char_end: number | null;
            /** Page */
            page: number | null;
        };
        /** CompileFilterIn */
        CompileFilterIn: {
            /** Query */
            query: string;
        };
        /** CrawlerRunOut */
        CrawlerRunOut: {
            /** Run Id */
            run_id: number;
            /** Target Date */
            target_date: string | null;
            /** Status */
            status: string;
            /** Fetched */
            fetched: number;
            /** Saved */
            saved: number;
            /** Error Code */
            error_code: number | null;
            /** Error Message */
            error_message: string | null;
            /** Raw */
            raw: {
                [key: string]: unknown;
            } | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /** CrawlerRunsOut */
        CrawlerRunsOut: {
            /** Items */
            items: components["schemas"]["CrawlerRunOut"][];
        };
        /** DeadLetterOut */
        DeadLetterOut: {
            /** Message Id */
            message_id: string;
            /** Event */
            event: string;
            /** Error */
            error: string | null;
            /** Retry Stage */
            retry_stage: string | null;
            /** Failed At */
            failed_at: string | null;
        };
        /** DigestDatesOut */
        DigestDatesOut: {
            /** Dates */
            dates: string[];
        };
        /** DocumentChunksOut */
        DocumentChunksOut: {
            /** Document Id */
            document_id: number;
            /** Chunks */
            chunks: components["schemas"]["ChunkOutlineOut"][];
        };
        /** DocumentOut */
        DocumentOut: {
            /** Document Id */
            document_id: number;
            /** File Name */
            file_name: string | null;
            /** Doc Kind Name */
            doc_kind_name: string | null;
            /** File Size */
            file_size: number | null;
            /** Extraction Status */
            extraction_status: string;
            /** Page Count */
            page_count: number | null;
            /** Ocr Used */
            ocr_used: boolean;
            /** Char Count */
            char_count: number | null;
            /** Has Text */
            has_text: boolean;
        };
        /** DocumentPipelineOut */
        DocumentPipelineOut: {
            /** Funnel */
            funnel: components["schemas"]["PipelineStageOut"][];
            /** Failures */
            failures: components["schemas"]["PipelineStageOut"][];
        };
        /** DownloadOut */
        DownloadOut: {
            /** Url */
            url: string;
            /** File Name */
            file_name: string | null;
            /** Expires In */
            expires_in: number;
        };
        /** FacetBucketOut */
        FacetBucketOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /** FacetsOut */
        FacetsOut: {
            /** Total */
            total: number;
            /** Regions */
            regions: components["schemas"]["FacetBucketOut"][];
            /** Okpd2 */
            okpd2: components["schemas"]["FacetBucketOut"][];
            /** Customers */
            customers: components["schemas"]["FacetBucketOut"][];
            /** Price Histogram */
            price_histogram: components["schemas"]["PriceBucketOut"][];
            restrictive?: components["schemas"]["RestrictiveHintOut"] | null;
        };
        /** FeedbackIn */
        FeedbackIn: {
            /** Tender Id */
            tender_id: number;
            /** Signal */
            signal: string;
            /** Reason */
            reason?: string | null;
        };
        /** FilterOut */
        FilterOut: {
            /** Filter Id */
            filter_id: number;
            /** Name */
            name: string;
            /** Query */
            query: string;
            /** Spec */
            spec: {
                [key: string]: unknown;
            };
            /** In Digest */
            in_digest: boolean;
            /** Notify */
            notify: boolean;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Run At */
            last_run_at: string | null;
            /** Match Counts */
            match_counts: components["schemas"]["MatchCountOut"][];
        };
        /** FragmentOut */
        FragmentOut: {
            /** Chunk Id */
            chunk_id: number;
            /** Document Id */
            document_id: number;
            /** Tender Id */
            tender_id: number;
            /** Reg Num */
            reg_num: string;
            /** Tender Name */
            tender_name: string | null;
            /** Tender Price */
            tender_price: string | null;
            /** Document Name */
            document_name: string | null;
            /** Text */
            text: string;
            /** Char Start */
            char_start: number | null;
            /** Char End */
            char_end: number | null;
            /** Highlights */
            highlights: [
                number,
                number
            ][];
            scores: components["schemas"]["FragmentScoresOut"];
        };
        /** FragmentPageOut */
        FragmentPageOut: {
            /** Items */
            items: components["schemas"]["FragmentOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * FragmentScoresOut
         * @description Разложение оценки: видно, какая часть поиска нашла фрагмент.
         */
        FragmentScoresOut: {
            /** Lexical */
            lexical: number | null;
            /** Vector */
            vector: number | null;
            /** Rrf */
            rrf: number;
        };
        /** GroupBucketOut */
        GroupBucketOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Count */
            count: number;
            /** Total Price */
            total_price?: string | null;
        };
        /**
         * GroupsOut
         * @description Оглавление сгруппированного списка: по шапке на группу.
         */
        GroupsOut: {
            /** Field */
            field: string;
            /** Items */
            items: components["schemas"]["GroupBucketOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Services */
            services: components["schemas"]["ServiceHealthOut"][];
        };
        /** MatchCountOut */
        MatchCountOut: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Count */
            count: number;
        };
        /** PageOut */
        PageOut: {
            /** Items */
            items: components["schemas"]["TenderOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number | null;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * PatchFilterIn
         * @description Частичное изменение. Не переданное поле не трогается.
         */
        PatchFilterIn: {
            /** Name */
            name?: string | null;
            /** Spec */
            spec?: {
                [key: string]: unknown;
            } | null;
            /** In Digest */
            in_digest?: boolean | null;
            /** Notify */
            notify?: boolean | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** PipelineStageOut */
        PipelineStageOut: {
            /** Stage */
            stage: string;
            /** Count */
            count: number;
        };
        /** PriceBucketOut */
        PriceBucketOut: {
            /** Price From */
            price_from: string;
            /** Price To */
            price_to: string;
            /** Count */
            count: number;
        };
        /** QueueStatOut */
        QueueStatOut: {
            /** Name */
            name: string;
            /** Depth */
            depth: number;
            /** Consumers */
            consumers: number;
            /** Dead Letters */
            dead_letters: number;
        };
        /** QueuesOut */
        QueuesOut: {
            /** Queues */
            queues: components["schemas"]["QueueStatOut"][];
            /** Retry Ladder */
            retry_ladder: components["schemas"]["RetryStageOut"][];
            /** Dead Letters */
            dead_letters: components["schemas"]["DeadLetterOut"][];
        };
        /** RatingHistoryOut */
        RatingHistoryOut: {
            /** Items */
            items: components["schemas"]["RatingOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** RatingOut */
        RatingOut: {
            /** Signal Id */
            signal_id: number;
            /** Tender Id */
            tender_id: number;
            /** Reg Num */
            reg_num: string;
            /** Name */
            name: string | null;
            /** Signal */
            signal: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RestrictiveHintOut
         * @description Какое условие отсекает больше всего и сколько нашлось бы без него.
         */
        RestrictiveHintOut: {
            /** Param */
            param: string;
            /** Kept */
            kept: number;
            /** Dropped */
            dropped: number;
        };
        /** RetryStageOut */
        RetryStageOut: {
            /** Stage */
            stage: string;
            /** Depth */
            depth: number;
        };
        /** RunFilterIn */
        RunFilterIn: {
            /** Since */
            since?: string | null;
            /** Tender Ids */
            tender_ids?: number[];
        };
        /** SaveFilterIn */
        SaveFilterIn: {
            /** Name */
            name: string;
            /** Query */
            query: string;
            /** Spec */
            spec?: {
                [key: string]: unknown;
            } | null;
        };
        /** ServiceHealthOut */
        ServiceHealthOut: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Port */
            port: number | null;
            /** P95 Ms */
            p95_ms: number | null;
            /** Facts */
            facts: {
                [key: string]: unknown;
            };
        };
        /** SettingsOut */
        SettingsOut: {
            /** Llm */
            llm: {
                [key: string]: unknown;
            };
            /** Crawler */
            crawler: {
                [key: string]: unknown;
            };
            /** Embedding */
            embedding: {
                [key: string]: unknown;
            };
            /** Certificates */
            certificates: components["schemas"]["CertificateOut"][];
            /** Eis Token */
            eis_token: {
                [key: string]: unknown;
            };
            /** Restart Required Keys */
            restart_required_keys: string[];
        };
        /** SimilarOut */
        SimilarOut: {
            /** Items */
            items: components["schemas"]["SimilarTenderOut"][];
        };
        /** SimilarTenderOut */
        SimilarTenderOut: {
            tender: components["schemas"]["TenderOut"];
            /** Similarity */
            similarity: number;
            /** Driver */
            driver: string;
        };
        /** TenderDetailOut */
        TenderDetailOut: {
            tender: components["schemas"]["TenderOut"];
            /** Documents */
            documents: components["schemas"]["DocumentOut"][];
            /** Verdicts */
            verdicts: {
                [key: string]: unknown;
            }[];
        };
        /** TenderEventOut */
        TenderEventOut: {
            /** Message Id */
            message_id: string;
            /** Event */
            event: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Status */
            status: string;
            /** Attempt */
            attempt: number;
            /** Retry Stage */
            retry_stage: string | null;
            /** Error */
            error: string | null;
        };
        /** TenderEventsOut */
        TenderEventsOut: {
            /** Items */
            items: components["schemas"]["TenderEventOut"][];
        };
        /** TenderOut */
        TenderOut: {
            /** Tender Id */
            tender_id: number;
            /** Reg Num */
            reg_num: string;
            /** Name */
            name: string | null;
            /** Description */
            description: string | null;
            /** Price */
            price: string | null;
            /** Currency */
            currency: string | null;
            /** Customer Name */
            customer_name: string | null;
            /** Customer Inn */
            customer_inn: string | null;
            /** Okpd2 Code */
            okpd2_code: string | null;
            /** Okpd2 Name */
            okpd2_name: string | null;
            /** Region Code */
            region_code: string | null;
            /** Publish Date */
            publish_date: string | null;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** Prev End Date */
            prev_end_date: string | null;
            /** Deadline Changed */
            deadline_changed: boolean;
            /** Status */
            status: string | null;
            /** Documents Status */
            documents_status: string;
            /** Document Count */
            document_count: number;
            /** Relevance */
            relevance?: number | null;
        };
        /** TestFilterIn */
        TestFilterIn: {
            /**
             * Days
             * @default 30
             */
            days: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ViewIn */
        ViewIn: {
            /** Tender Id */
            tender_id: number;
            /** Dwell Ms */
            dwell_ms?: number | null;
        };
        /** WeightPatchIn */
        WeightPatchIn: {
            /**
             * Facet
             * @default okpd2
             */
            facet: string;
            /** Key */
            key: string;
            /** Weight */
            weight?: number | null;
        };
        /** WinIn */
        WinIn: {
            /** Tender Id */
            tender_id: number;
            /** Won At */
            won_at?: string | null;
            /** Contract Price */
            contract_price?: number | string | null;
            /** Notes */
            notes?: string | null;
        };
        /** WinOut */
        WinOut: {
            /** Tender Id */
            tender_id: number;
            /** Reg Num */
            reg_num: string;
            /** Name */
            name: string | null;
            /** Won At */
            won_at: string | null;
            /** Contract Price */
            contract_price: string | null;
            /** Notes */
            notes: string | null;
        };
        /** WinsOut */
        WinsOut: {
            /** Items */
            items: components["schemas"]["WinOut"][];
            /** Total Value */
            total_value: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_tenders_tenders_get: {
        parameters: {
            query?: {
                q?: string | null;
                price_min?: number | string | null;
                price_max?: number | string | null;
                /** @description Префикс кода ОКПД2 */
                okpd2?: string | null;
                region?: string[] | null;
                customer_inn?: string | null;
                since?: string | null;
                until?: string | null;
                only_active?: boolean;
                /** @description Срок подачи сдвигался */
                deadline_changed?: boolean;
                documents_status?: ("pending" | "processing" | "done" | "partial" | "failed") | null;
                /** @description Есть ли у закупки распознанный текст документов */
                has_text?: boolean | null;
                /** @description Только прошедшие LLM-фильтр */
                filter_id?: number | null;
                /** @description Номер страницы (offset-режим) */
                page?: number;
                page_size?: number;
                /** @description Курсор последней строки. Задан — `page` игнорируется, `page` в ответе null */
                cursor?: string | null;
                /** @description Размер страницы курсором */
                limit?: number | null;
                /** @description Порядок выдачи. Одно поле (`price`) или список ключей с направлениями (`okpd:asc,price:desc`). Добор по `id` сервер дописывает сам. */
                sort?: string;
                order?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_tenders_tenders_search_get: {
        parameters: {
            query: {
                /** @description Запрос: лексика + смысл */
                q: string;
                price_min?: number | string | null;
                price_max?: number | string | null;
                okpd2?: string | null;
                region?: string[] | null;
                since?: string | null;
                until?: string | null;
                only_active?: boolean;
                /** @description Номер страницы (offset-режим) */
                page?: number;
                page_size?: number;
                /** @description Курсор последней строки. Задан — `page` игнорируется, `page` в ответе null */
                cursor?: string | null;
                /** @description Размер страницы курсором */
                limit?: number | null;
                /** @description Порядок выдачи. Одно поле (`price`) или список ключей с направлениями (`okpd:asc,price:desc`). Добор по `id` сервер дописывает сам. */
                sort?: string;
                order?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tender_facets_tenders_facets_get: {
        parameters: {
            query?: {
                q?: string | null;
                price_min?: number | string | null;
                price_max?: number | string | null;
                okpd2?: string | null;
                region?: string[] | null;
                customer_inn?: string | null;
                since?: string | null;
                until?: string | null;
                only_active?: boolean;
                deadline_changed?: boolean;
                documents_status?: ("pending" | "processing" | "done" | "partial" | "failed") | null;
                /** @description Есть ли у закупки распознанный текст документов */
                has_text?: boolean | null;
                filter_id?: number | null;
                /** @description Посчитать, какое условие отсекает больше всего */
                explain_empty?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacetsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tender_groups_tenders_groups_get: {
        parameters: {
            query: {
                /** @description Поле группировки: okpd | customer | region */
                group: string;
                q?: string | null;
                price_min?: number | string | null;
                price_max?: number | string | null;
                okpd2?: string | null;
                region?: string[] | null;
                customer_inn?: string | null;
                since?: string | null;
                until?: string | null;
                only_active?: boolean;
                deadline_changed?: boolean;
                documents_status?: ("pending" | "processing" | "done" | "partial" | "failed") | null;
                /** @description Есть ли у закупки распознанный текст документов */
                has_text?: boolean | null;
                filter_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tender_tenders__reg_num__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reg_num: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_tenders_tenders__reg_num__similar_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                reg_num: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tender_events_tenders__reg_num__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reg_num: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderEventsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_document_documents__document_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_text_documents__document_id__text_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_chunks_documents__document_id__chunks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentChunksOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_filters_filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterOut"][];
                };
            };
        };
    };
    save_filter_filters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveFilterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_filter_filters__filter_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_filter_filters__filter_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_filter_filters__filter_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filter_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchFilterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compile_filter_filters_compile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompileFilterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_filter_filters__filter_id__duplicate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_filter_filters__filter_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filter_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunFilterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_filter_filters__filter_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filter_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestFilterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_status_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_fragments_search_fragments_get: {
        parameters: {
            query: {
                /** @description Запрос по тексту документации */
                q: string;
                /** @description lexical | semantic | rrf */
                mode?: "lexical" | "semantic" | "rrf";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FragmentPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    digest_dates_digest_get: {
        parameters: {
            query: {
                /** @description Начало периода */
                from: string;
                /** @description Конец периода */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestDatesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    digest_digest__digest_date__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                digest_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_digest_digest__digest_date__post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                digest_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommendations_recommendations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    view_views_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    win_wins_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WinIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    profile_weights_profile_weights_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    patch_profile_weight_profile_weights_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeightPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_ranker_profile_ranker_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    profile_history_profile_history_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingHistoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_wins_profile_wins_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WinsOut"];
                };
            };
        };
    };
    delete_rating_profile_history__signal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    services_health_monitoring_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    queues_monitoring_queues_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuesOut"];
                };
            };
        };
    };
    retry_dead_letter_monitoring_queues_dead_letters__message_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crawler_runs_monitoring_crawler_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlerRunsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_pipeline_monitoring_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPipelineOut"];
                };
            };
        };
    };
    settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    confirm_token_rotation_settings_eis_token_rotated_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
